name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of machine to run the job on.
    runs-on: ubuntu-latest

    # A job contains a sequence of tasks called steps
    steps:
      # Selects an action to run as part of a step in your job.
      - uses: actions/checkout@v2

      # A name for your step to display on GitHub.
      - name: Runs only on pull request
        run: echo is pull request event ${{ to_json(github) }}
        if: ${{ github.event_name == 'pull_request' }}

      - name: Runs only if push
        run: echo is push event
        if: ${{ github.event_name == 'push' }}

      - name: Runs a multi-line script
        run: |
          echo Add other actions to build, 
          echo test, and deploy your project
