name: Manual

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
        required: true

jobs:
  printInputs:
    runs-on: ubuntu-latest
    # only allows to run on master
    if: github.ref == 'refs/heads/master'

    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
